### ISSUE TITLE
Some inspiration from the DOM Spec

### ISSUE THREAD

**Issue by LinusU** [refractproject/refract-spec#21]
I think that refract is a great idea, but I find some of the naming to be really confusing. Especially `element` which took me a while to understand that it's the type of the element, and that the element is that properties parent object.

`content` is also subpar in the sense that it can be an array, an object or a string. Or it really can be anything at all. I think that it's better to always have an array of the child elements.

I also think that `node` is a better name than `element`, but maybe that's just me.

What I propose is that we draw some inspiration from the DOM specification that has been thru the scrutiny of thousands of eyes.

Following there naming and thinking would yield something like this. This simple json:

``` json
{
  "name": "John Doe",
  "email": "john@example.com"
}
```

Would be parsed into this ast:

``` json
{
  "nodeType": "object",
  "childNodes": [{
    "nodeType": "string",
    "nodeName": "name",
    "textContent": "John Doe"
  }, {
    "nodeType": "string",
    "nodeName": "email",
    "textContent": "john@example.com"
  }]
}
```

This simple xml:

``` xml
<Person name="John Doe" email="john@example.com" />
```

Would be parsed into this ast:

``` json
{
  "nodeType": "element",
  "attributes": {
    "name": "John Doe",
    "email": "john@example.com"
  }
}
```

A bit more complicated json:

``` json
[{
  "name": "Linus",
  "year": 1992
}, {
  "name": "Bob",
  "year": 1941
}, {
  "name": "Steve",
  "year": 1955
}]
```

Would parse into this ast:

``` json
{
  "nodeType": "array",
  "childNodes": [{
    "nodeType": "object",
    "childNodes": [{
      "nodeType": "string",
      "nodeName": "name",
      "textContent": "Linus"
    },{
      "nodeType": "number",
      "nodeName": "year",
      "nodeValue": 1992
    }]
  }, {
    "nodeType": "object",
    "childNodes": [{
      "nodeType": "string",
      "nodeName": "name",
      "textContent": "Bob"
    },{
      "nodeType": "number",
      "nodeName": "year",
      "nodeValue": 1941
    }]
  }, {
    "nodeType": "object",
    "childNodes": [{
      "nodeType": "string",
      "nodeName": "name",
      "textContent": "Steve"
    },{
      "nodeType": "number",
      "nodeName": "year",
      "nodeValue": 1955
    }]
  }]
}
```

Something like this would be the specification for `Node`:
### Node (object)
- `nodeType` (string, required) type of the element
- `nodeName` (string) name of the element
- `attributes` (object[string, string]) list of attributes
- One Of:
  - `childNodes` (array[Node], required) list of children (when `nodeType` is `element`, `array` or `object`)
  - `textContent` (string, required) text content of this node (when `nodeType` is `string`)
  - `nodeValue` (number, required) numerical value of this node (when `nodeType` is `number` or `boolean`)

What do you guys think?

**Comment by LinusU** [comment]
If you don't like the explicit `node*` naming something like this might be more appropriate:
- `type` (string, required) type of the element
- `name` (string) name of the element
- `attributes` (object[string, string]) element attributes
- One of:
  - `children` (array[Node], required) list of children
  - `value` (enum) element value
    - Members
      - (null)
      - (string)
      - (number)
      - (boolean)

**Comment by zdne** [comment]
Thanks for sharing some thoughts @LinusU ! I believe we (with @smizell)  should explain some design decisions and principles more in-depth. 

Here is my take: 
- `type` vs. `element` 
  Refract is essentially a fractal – recursive elements – while it may be a tree it may be also infinitely recursive – that is maybe why the DOM – terminology doesn't fit the best (albeit I am occasionally using it)
- `name` - to address this need we have came with a `meta` property that is meant to be reserved for refract use only. You can as attributes reserved to refract (they are separate to not pollute "namespace" in `attributes` property).
- as for the `content` I am not quite sure where do you see the problem – the `content`s content maybe be really anything from primitives to refracted primitives to complex structures.

Pretty much everything can be "refracted" or used "as is". That is the main idea of refract. Element's semantics – the libraries manipulating refract (see minim.js) should be taking this into account.

Anyway maybe @smizell may have some better explanation... :monkey_face:

**Comment by LinusU** [comment]
Recursive elements is interesting, I hadn't understood that 'til now. I still feel that maybe `elementType` would be better than `element` since it describes what it is better; or just `type`.

Maybe I'm seeing this from the API Blueprint POW and not seeing the bigger picture, and that is why I feel that it feels a bit over-engineered.

**Comment by smizell** [comment]
@LinusU Thanks for the input here, and sorry for the delay. I've been traveling a bit and then trying to catch up. I'll do my best to explain a little bit where these ideas came from, but would also like to think more on your thoughts and recommendations.

You may have seen this, but I recently updated the [README on the spec repo](https://github.com/refractproject/refract-spec) to provide some extra explanation of Refract. If you haven't, it might be a good start before continuing with this writeup.

Refract grew from a desire to have one data structure in JSON that could be used to describe all kinds of semantic data across all kinds of domains. We've found that coupling your data to the structure of your document makes for difficult evolvability of both the document itself and the client consuming the document. In HTML, you have this separation with things like jQuery and CSS selectors, which allows you to move your structure around yet keep the same semantics. We wanted this for our JSON documents to allow us to have the same document structure for multiple semantic namespaces.

I'm honestly not sure how we decided on the name of `element` :) Elements have many different uses and meanings. Elements may be data, elements may be new element definitions, and elements may even be computational elements. Let me explain that a bit.

First, elements as data is the simplest of uses.

``` json
["string", {}, {}, "foobar"]
```

Using an `id`, you can declare new definitions of elements and data at the same time. So here is data, but it is also declaring a new type of element. This says that you can now use the `newElement` and it should act as a string. This is very similar to how MSON works.

``` json
["string", { "id": "newElement" }, {}, "foobar"]
```

Now using the new element.

``` json
["newElement", {}, {}, "abcd"]
```

Just a quick pause here to mention why we separated `meta` and `attributes`. The `meta` object is for Refract purposes only. We've added things for addressability of elements and meta data for elements here that can be used across all elements and namespaces. The `attributes` object is then left for user-specified semantics.

Continuing on, elements may also be computational. I like to think of Refract as a LISP-style structure (sorry @zdne). I was actually thinking of a LISP-like structure for things before we made our way to Refract. LISP is just list processing, but the lists actually contain declarative code as well.

Consider the `extend` element that basically combines multiple elements into a single element.

``` json
["extend", {}, {}, [
  ["string", {}, { "foo": "bar"}, null],
  ["string", {}, {}, "abcd"]
]
```

This is semantically equivalent to:

``` json
["string", {}, { "foo": "bar"}, "abcd"]
```

In light of the idea that this element can be many different things, from data to code and even everything at the same time, I do not think of the first item in the list as a type, but rather as a reference to the actual element being used. If you're familiar with LISP, this is how it works as well, where the first item is not a type of the list but rather an actual function that may be passed around and referenced.

Hope that makes sense. Please feel free to continue to ask questions on this because you're really helping us work through this :) I'll also spend some time soon thinking through your ideas here (thanks again!).

**Comment by smizell** [comment]
@LinusU @zdne After some thought here, I think one way we could address the confusion and not break our current implementation is to refer to the element as something other than element. So while the now-Element has element, meta, attributes, and content, could we call all of those in their entirety something different?

We already have code in one of libraries that says `element.element`, so it does look quite odd.

I have some thoughts on what to call it, but I don't want to tarnish your creativity :) And while this doesn't align with the DOM, it may be a solution to provide better semantics.

Thoughts?

**Comment by LinusU** [comment]
@smizell @zdne I still don't see the problem with renaming the `.element` attribute to `.type`

> Here is my take:
> - type vs. element 
>   Refract is essentially a fractal – recursive elements – while it may be a tree it may be also infinitely recursive – that is maybe why the DOM – terminology doesn't fit the best (albeit I am occasionally using it)

I don't think that this explains it enough, why can't recursive elements have a `type`?

Sorry if I'm missing something already explained...

**Comment by zdne** [comment]
Note I would love to avoid over-used words like "type" or "class".

**Comment by LinusU** [comment]
Do you mind explaining why you would want that?

How about `elementType`?

**Comment by smizell** [comment]
I too do not like `type` or `class` because they have specific meanings in specific contexts. Though element may have the same issue.

I like to think of this:

``` json
["string", {}, {} "foobar"]
```

As being:

``` javascript
string({}, {}, "foobar")
```

or 

``` javascript
var str = new String({}, {}, "foobar");
```

or 

``` clojure
(string {} {} "foobar")
```

The `element` is referencing something that is already defined, and you compute the valued depending on the context. This becomes even more obvious with the `extend` element.

``` javascript
var a = object({}, { foo: 'bar' }, { a: 1 });
var b = object({}, { foo: 'baz' }, { b: 2 });
var c = extend({}, {}, [a, b]); // equivalent to: object({}, { foo: 'baz' }, { a: 1, b: 2 });
```

This is why `type` has always felt funny to me. Hope that isn't crazy confusing :)

**Comment by LinusU** [comment]
It might be because the weekend has basically started but that sounded crazy confusing :)

Shouldn't `class` be a perfect fit for the cases you are describing? What specific meanings do `type` and `class` have in specific contexts?

Do you mean that the meaning isn't clear by the name itself? That it's hard to know what `type` is, but you know what `element.type` is?

That could be solved by naming it `.elementType`. However, I think that the same could be said about both `element` and `content`. When I see something named `element`, I expect that to contain an element. Not a string representing what type of element it is. This view is further strengthen by the fact that the parent is named `element` as well.

Seeing the variables all by itself becomes a bit awkward as well, consider the following example.

``` javascript
function makePerson (name, gender) {
  var element = 'person'
  var attributes = { name, gender }
  var element = { element, attributes }

  validatePersonElement(element)

  return element
}
```

I'm declaring `element` twice here which, although it works, is very bad practice. Now my options is to either change the name of the element type, or change the name of the element itself. I naturally arrive at changing the element type to `elementType` which now leads to the following object.

``` javascript
{ element: elementType, attributes }
```

Consider instead if the type was simply named `type`.

``` javascript
function makePerson (name, gender) {
  var type = 'person'
  var attributes = { name, gender }
  var element = { type, attributes }

  validatePersonElement(element)

  return element
}
```

**Comment by smizell** [comment]
Good example :)

But I think the goal is to treat the JSON as a representation of the internal model, but not as the internal model. The way we are doing it is this:

``` javascript
var person = new PersonElement('John Doe', 'male');
person.validate();
person.toRefract();
```

This would require that you extend some primitive for defining `PersonElement`. We'll just use a string.

``` javascript
var PersonElement = StringElement.extend({
  constructor: function(name, gender) {
    this.__super();
    this.attributes.set({
      name: name,
      gender: gender
    });
  },

  validate: function() {
    // your validation code here
  }
});
```

This is a WIP and this syntax above isn't ready, but the intention is to provide an interface so you aren't working directly with the structure. It should be abstracted away.

**Comment by smizell** [comment]
@LinusU Wanted to circle back that we have implemented the above API for [Minim](https://github.com/refractproject/minim).

I also wanted to mention that we are looking at decoupling JSON representations from actual Refract implementations. This means, that you could actually define a spec for the representation in the way you've defined above and provide some adapter for converting to/from it. If you are interested in doing this, feel free to do so here and we'll think through it with you:

https://github.com/refractproject/rfcs

I do not think we'll be focusing on other representations for a while, but if you are interested in working on this, you are welcome to do so. :)

**Comment by smizell** [comment]
I'm going to propose we move this to an RFC for discussion if there is still interest here.

https://github.com/refractproject/rfcs

Will be closing for now, but that does not mean we're not interested in chatting about this :)
